import { AppRole } from "@/generated/prisma/client";
import { Notice } from "@/components/notice";
import { SubmitButton } from "@/components/submit-button";
import { requireAccess } from "@/lib/access";
import { formatLocalDateTime } from "@/lib/dates";
import { getServerEnv } from "@/lib/env";
import { prisma } from "@/lib/db";
import { createFinancialAccountAction, createInvitationAction, saveRehearsalRecurrenceAction, setUserAccessAction } from "./actions";

const roles = Object.values(AppRole);

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string; invite?: string }> }) {
  await requireAccess([AppRole.SUPERADMIN]);
  const params = await searchParams;
  const [users, members, sections, invitations, accounts, recurrence] = await Promise.all([
    prisma.user.findMany({ include: { roles: true, sectionScopes: true, member: true }, orderBy: { name: "asc" } }),
    prisma.member.findMany({ where: { authUserId: null }, orderBy: { displayName: "asc" } }),
    prisma.voiceSection.findMany({ where: { isActive: true }, orderBy: { sortOrder: "asc" } }),
    prisma.invitation.findMany({ orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.financialAccount.findMany({ orderBy: { name: "asc" } }),
    prisma.appSetting.findUnique({ where: { key: "rehearsalRecurrence" } }),
  ]);
  const recurrenceValue = recurrence?.value as { enabled?: boolean; weekday?: number; time?: string; durationMinutes?: number; openBeforeMinutes?: number; closeAfterMinutes?: number; sectionId?: string | null } | null;
  const inviteUrl = params.invite ? new URL(`/invitacion/${params.invite}`, getServerEnv().APP_BASE_URL).toString() : null;
  return <div className="page"><header className="page-header"><div><p className="eyebrow">Administración segura</p><h1>Configuración</h1><p className="lede">No hay autorregistro. Los cambios de rol revocan todas las sesiones del usuario.</p></div></header><Notice success={params.success} error={params.error}/>
    {inviteUrl ? <div className="notice notice-success"><strong>Enlace de un solo uso:</strong><br/><span className="mono small">{inviteUrl}</span><br/>Compártelo por un canal privado. Caduca en 48 horas.</div> : null}
    <section className="grid grid-2"><article className="card"><h2>Crear invitación</h2><form action={createInvitationAction} className="form-grid"><div className="field"><label>Correo</label><input name="email" type="email" required/></div><div className="field"><label>Rol inicial</label><select name="role" defaultValue="MIEMBRO">{roles.map((role) => <option key={role} value={role}>{role}</option>)}</select></div><div className="field field-full"><label>Vincular ficha, si corresponde</label><select name="memberId"><option value="">Sin ficha vinculada</option>{members.map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></div><SubmitButton>Crear enlace</SubmitButton></form></article><article className="card"><h2>Nueva cuenta financiera</h2><form action={createFinancialAccountAction} className="form-grid"><div className="field"><label>Nombre</label><input name="name" required minLength={3}/></div><div className="field"><label>Tipo</label><select name="kind"><option value="BANK">Banco</option><option value="CASH">Efectivo</option><option value="SAVINGS">Ahorro</option></select></div><SubmitButton>Crear sin saldo inicial</SubmitButton></form><p className="muted small">Las aperturas requieren evidencia y se registran aparte.</p></article></section>
    <section className="section card"><h2>Recurrencia de ensayos</h2><p className="muted small">Se aplica solo después de configurarla; no se presupone día ni hora.</p><form action={saveRehearsalRecurrenceAction} className="form-grid"><label><input type="checkbox" name="enabled" defaultChecked={recurrenceValue?.enabled} style={{width:"auto",minHeight:"auto"}}/> Activar generación semanal</label><div className="field"><label>Día</label><select name="weekday" defaultValue={recurrenceValue?.weekday ?? 6}><option value="0">Domingo</option><option value="1">Lunes</option><option value="2">Martes</option><option value="3">Miércoles</option><option value="4">Jueves</option><option value="5">Viernes</option><option value="6">Sábado</option></select></div><div className="field"><label>Hora local</label><input name="time" type="time" defaultValue={recurrenceValue?.time ?? ""} required/></div><div className="field"><label>Duración min</label><input name="durationMinutes" type="number" min="1" max="480" defaultValue={recurrenceValue?.durationMinutes ?? 120}/></div><div className="field"><label>Abrir antes min</label><input name="openBeforeMinutes" type="number" min="0" max="480" defaultValue={recurrenceValue?.openBeforeMinutes ?? 30}/></div><div className="field"><label>Cerrar después min</label><input name="closeAfterMinutes" type="number" min="0" max="480" defaultValue={recurrenceValue?.closeAfterMinutes ?? 30}/></div><div className="field"><label>Convocatoria</label><select name="sectionId" defaultValue={recurrenceValue?.sectionId ?? ""}><option value="">Todos los activos</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.name}</option>)}</select></div><SubmitButton>Guardar recurrencia</SubmitButton></form></section>
    <section className="section grid">{users.map((user) => <article className="card" key={user.id}><div className="section-header"><div><strong>{user.name}</strong><br/><span className="muted small">{user.email} · {user.member?.displayName ?? "sin ficha"}</span></div></div><form action={setUserAccessAction} className="form-grid"><input type="hidden" name="userId" value={user.id}/><fieldset className="field"><legend>Roles</legend><div className="actions">{roles.map((role) => <label key={role}><input type="checkbox" name="roles" value={role} defaultChecked={user.roles.some((item) => item.role === role)} style={{width:"auto",minHeight:"auto"}}/> {role}</label>)}</div></fieldset><fieldset className="field"><legend>Cuerdas para jefe</legend><div className="actions">{sections.map((section) => <label key={section.id}><input type="checkbox" name="sectionIds" value={section.id} defaultChecked={user.sectionScopes.some((scope) => scope.sectionId === section.id)} style={{width:"auto",minHeight:"auto"}}/> {section.name}</label>)}</div></fieldset><SubmitButton>Actualizar y revocar sesiones</SubmitButton></form></article>)}</section>
    <section className="section grid grid-2"><article className="card"><h2>Invitaciones recientes</h2>{invitations.length ? invitations.map((invitation) => <p key={invitation.id}><strong>{invitation.email}</strong><br/><span className="muted small">{invitation.role} · vence {formatLocalDateTime(invitation.expiresAt)} · {invitation.consumedAt ? "usada" : "pendiente"}</span></p>) : <p className="empty">Sin invitaciones.</p>}</article><article className="card"><h2>Cuentas</h2>{accounts.length ? accounts.map((account) => <p key={account.id}><strong>{account.name}</strong> <span className="pill">{account.kind}</span></p>) : <p className="empty">Sin cuentas financieras.</p>}</article></section>
  </div>;
}
